<script setup lang="ts">
import { nextTick, ref } from 'vue'
import type { ChatMessage } from '@/types/api'
const prompts=[['深伪和普通修图有何区别？','深度伪造和普通修图有什么区别？'],['视频检测为何不能只看单帧？','为什么视频检测不能只看单帧画面？'],['热力图、关键帧、曲线怎么读？','热力图、关键帧和概率曲线怎么看？'],['疑似 AI 换脸先看什么？','遇到疑似AI换脸内容，应该先看什么？']]
const fixed:Record<string,string>={
 '深度伪造和普通修图有什么区别？':'一句话：普通修图是“润色原内容”，深度伪造是“生成并冒充真实身份或事件”。\n\n可从目标、技术、风险和证据四个维度区分。遇到催转账、催验证码或催下载软件时，先暂停操作并独立核验身份。',
 '为什么视频检测不能只看单帧画面？':'核心原因：深伪很多破绽不在某一帧，而在帧与帧之间的连续关系。\n\n视频检测需要综合边界稳定性、时序纹理、音画同步、动作物理性和上下文一致性。',
 '热力图、关键帧和概率曲线怎么看？':'建议按“曲线 -> 帧 -> 区域”三步看。\n\n先看概率曲线的整体趋势，再回看高风险关键帧，最后用热力图定位模型关注区域。热力图只是关注提示，不能单独作为伪造证明。',
 '遇到疑似AI换脸内容，应该先看什么？':'先做身份核验，不要先陷入画面争论。\n\n先暂停转账、验证码和屏幕共享；再通过已知号码或共同联系人核身；随后检查内容证据并保留原文件和时间戳。',
}
const messages=ref<ChatMessage[]>([]), question=ref(''), sending=ref(false), error=ref(''), thread=ref<HTMLElement|null>(null)
function scroll(){nextTick(()=>thread.value?.scrollTo({top:thread.value.scrollHeight}))}
async function submit(value?:string){const text=(value??question.value).trim();if(!text||sending.value)return;question.value='';error.value='';const history=messages.value.slice(-6);messages.value.push({role:'user',content:text});const answer={role:'assistant' as const,content:''};messages.value.push(answer);scroll();if(fixed[text]){answer.content=fixed[text];scroll();return}sending.value=true;try{const response=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json',Accept:'text/event-stream'},body:JSON.stringify({question:text,history})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message||'问答服务暂不可用');const reader=response.body?.getReader();if(!reader)throw new Error('浏览器未收到流式响应');const decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const name=event.split('\n').find(x=>x.startsWith('event:'))?.slice(6).trim();const raw=event.split('\n').filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).join('\n');if(!raw)continue;const data=JSON.parse(raw);if(name==='delta'){answer.content+=data.content||'';scroll()}else if(name==='done'&&!answer.content)answer.content=data.answer||'';else if(name==='error')throw new Error(data.message)}}}catch(e){messages.value.pop();error.value=e instanceof Error?e.message:'问答失败'}finally{sending.value=false;scroll()}}
function keydown(e:KeyboardEvent){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}
</script>
<template><section class="chat-app"><aside class="chat-sidebar"><div class="chat-sidebar__brand"><p class="eyebrow">Deepfake Copilot</p><h1>深度伪造检测问答</h1><p>面向深度伪造检测场景的专用知识问答。</p></div><RouterLink class="chat-sidebar__back" to="/">返回首页</RouterLink><div class="chat-sidebar__scope"><strong>检测原理、异常迹象、结果解读、答辩表达</strong><p>不把文本问答伪装成实时检测，也不回答与深度伪造无关的话题。</p></div><div class="chat-sidebar__section"><span class="chat-sidebar__label">快捷问题</span><div class="chat-sidebar__prompts"><button v-for="prompt in prompts" :key="prompt[0]" class="chat-sidebar__prompt" type="button" @click="submit(prompt[1])">{{ prompt[0] }}</button></div></div><div class="chat-sidebar__foot"><span>Enter 发送</span><span>Shift + Enter 换行</span></div></aside><div class="chat-main" :class="{'is-conversation':messages.length}"><div ref="thread" class="chat-canvas" aria-live="polite"><section v-if="!messages.length" class="chat-empty"><p class="chat-empty__eyebrow">Start A Conversation</p><h2>想了解深度伪造？从这里开始</h2><p class="chat-empty__lede">可以从检测原理、案例辨别、结果解读、风险防范这四个高频问题开始。</p><div class="chat-empty__signals"><div><span>01</span><strong>原理入门</strong><p>深伪如何生成，检测在关注哪些异常线索？</p></div><div><span>02</span><strong>案例辨别</strong><p>疑似 AI 换脸或换声时，普通人先看哪些细节？</p></div><div><span>03</span><strong>结果解读</strong><p>热力图、关键帧、概率曲线各自说明什么？</p></div><div><span>04</span><strong>风险防范</strong><p>遇到可疑内容，怎样核验信息并降低误判风险？</p></div></div></section><article v-for="(message,index) in messages" :key="index" class="chat-message" :class="`chat-message--${message.role}`"><div class="chat-message__meta">{{ message.role==='user'?'你':'AI 助手' }}</div><div class="chat-message__body chat-rich-text"><p v-for="line in message.content.split('\n')" :key="line">{{ line || '\u00a0' }}</p><p v-if="!message.content" class="vue-loading">正在思考...</p></div></article></div><div class="chat-dock"><p v-if="error" class="chat-status">{{ error }}</p><form class="chat-composer" @submit.prevent="submit()"><textarea v-model="question" class="chat-composer__input" rows="1" maxlength="2000" placeholder="请输入你想了解的问题，例如：什么是 AI 换脸？" @keydown="keydown"/><button class="chat-composer__submit" type="submit" :disabled="sending">{{ sending?'生成中':'发送' }}</button></form></div></div></section></template>
