<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import type { EChartsCoreOption } from 'echarts/core'
import EChart from '@/components/EChart.vue'
import { api, errorMessage } from '@/services/api'
import type { HistoryBatch, HistorySummary } from '@/types/api'
const items=ref<HistoryBatch[]>([]), summary=ref<HistorySummary|null>(null), loading=ref(true), error=ref('')
const trend=computed<EChartsCoreOption>(()=>({tooltip:{trigger:'axis'},grid:{left:42,right:20,top:25,bottom:36},xAxis:{type:'category',data:summary.value?.recent_batches.map(x=>x.short_label||x.batch_name)},yAxis:{type:'value',min:0,max:1},series:[{type:'line',smooth:true,areaStyle:{opacity:.12},data:summary.value?.recent_batches.map(x=>x.suspicious_rate),itemStyle:{color:'#275efe'}}]}))
const risk=computed<EChartsCoreOption>(()=>({tooltip:{trigger:'axis'},legend:{bottom:0},grid:{left:42,right:20,top:25,bottom:48},xAxis:{type:'category',data:summary.value?.modalities.map(x=>x.file_type)},yAxis:{type:'value'},series:[{name:'全部样本',type:'bar',data:summary.value?.modalities.map(x=>x.item_count)},{name:'可疑样本',type:'bar',data:summary.value?.modalities.map(x=>x.fake_count),itemStyle:{color:'#ef6548'}}]}))
const latency=computed<EChartsCoreOption>(()=>({tooltip:{trigger:'axis'},grid:{left:42,right:20,top:25,bottom:36},xAxis:{type:'category',data:summary.value?.modalities.map(x=>x.file_type)},yAxis:{type:'value'},series:[{type:'bar',data:summary.value?.modalities.map(x=>x.avg_inference_time),itemStyle:{color:'#6457d7'}}]}))
onMounted(async()=>{try{[items.value,summary.value]=await Promise.all([api.history(),api.summary()])}catch(e){error.value=errorMessage(e)}finally{loading.value=false}})
</script>
<template><section class="history-shell"><div class="result-command"><div class="result-command__copy"><p class="eyebrow">History Overview</p><h1>历史记录中心</h1><p>汇总历次检测任务、批次摘要与结果入口，支持在答辩前快速回看已跑通的样例。</p></div></div><p v-if="loading" class="inline-status inline-status--pending">正在加载历史记录...</p><p v-else-if="error" class="inline-status inline-status--error">{{ error }}</p><template v-if="summary"><div class="metric-band"><div class="metric-tile"><span>任务数</span><strong>{{ summary.total_tasks }}</strong></div><div class="metric-tile"><span>累计文件数</span><strong>{{ summary.total_samples }}</strong></div><div class="metric-tile"><span>累计可疑数</span><strong>{{ summary.total_fake_samples }}</strong></div><div class="metric-tile"><span>整体可疑率</span><strong>{{ (summary.overall_suspicious_rate*100).toFixed(1) }}%</strong></div></div><div class="analytics-grid analytics-grid--history"><article class="surface-panel surface-panel--analytics chart-card chart-card--wide"><div class="panel-heading"><h2>最近 20 个批次可疑率趋势</h2><p>按批次回看系统近期风险波动，适合答辩时说明平台已经跑过哪些真实任务。</p></div><EChart v-if="summary.recent_batches.length" class="chart-shell" :option="trend"/><p v-else class="inline-note">暂无历史记录，趋势图将在首次检测后自动生成。</p></article><article class="surface-panel surface-panel--analytics chart-card"><div class="panel-heading"><h3>各模态样本与可疑样本对比</h3><p>横向比较图片、视频、音频三类历史样本规模和可疑样本量。</p></div><EChart v-if="summary.modalities.length" class="chart-shell" :option="risk"/><p v-else class="inline-note">暂无模态统计数据。</p></article><article class="surface-panel surface-panel--analytics chart-card"><div class="panel-heading"><h3>各模态平均推理耗时</h3><p>用于说明不同检测入口的计算开销差异。</p></div><EChart v-if="summary.modalities.length" class="chart-shell" :option="latency"/><p v-else class="inline-note">暂无耗时统计数据。</p></article></div></template><article class="surface-panel"><div class="panel-heading"><h2>批次列表</h2><p>优先从这里打开已验证的任务，减少现场临时上传的不确定性。</p></div><div v-if="items.length" class="table-shell"><table class="table"><thead><tr><th>时间</th><th>任务名</th><th>批次 ID</th><th>类型</th><th>文件数</th><th>可疑数</th><th>平均分</th><th>总耗时</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.task_id"><td>{{ item.created_at }}</td><td>{{ item.batch_name }}</td><td>{{ item.task_id }}</td><td>{{ item.file_type }}</td><td>{{ item.item_count }}</td><td>{{ item.fake_count }}</td><td>{{ item.avg_score.toFixed(4) }}</td><td>{{ item.total_inference_time.toFixed(4) }}</td><td><div class="table-links"><RouterLink :to="`/history/${item.task_id}`">批次详情</RouterLink><RouterLink :to="`/results/${item.task_id}`">结果页</RouterLink></div></td></tr></tbody></table></div><p v-else class="inline-note">暂无历史记录。</p></article></section></template>
