<script setup lang="ts">
const tracks=[
 {label:'概念',title:'Deepfake 不只是换脸，它是“合成 + 篡改 + 冒充”的统称',summary:'深度伪造通常指利用生成式模型，对图像、视频、音频进行合成、替换、重定向或伪造，使人误以为内容真实发生。',points:['常见形式包括人脸替换、口型驱动、语音克隆、虚拟主播、假截图和伪造通话录音。','它并不一定完全“从零生成”，很多案例只是把真实素材重新拼接、替换和包装。','真正危险的不是技术名词，而是它和社交工程结合后会快速突破人的信任防线。']},
 {label:'影像',title:'AI 换脸为什么容易让人上当',summary:'换脸内容往往借用真实视频的动作、环境和语气，只替换关键身份特征，所以第一眼更像“真的人在说话”。',points:['如果素材来自直播、短视频或会议录屏，观众会天然相信画面上下文是真实的。','平台压缩、低清转发、二次剪辑会掩盖边缘错位、肤色漂移和嘴型不稳等瑕疵。','诈骗场景里，对方通常不会给你充分时间慢慢观察画面，而是同步制造催促感。']},
 {label:'音频',title:'AI 换音的风险往往比换脸更隐蔽',summary:'语音克隆只需要较短样本就能模仿音色、语气和停顿习惯，电话场景里更容易让人忽略异常。',points:['声音“像”并不等于身份真实，来电显示、头像和备注名也都可能被伪造或盗用。','音频场景缺少画面佐证，人在焦虑或着急时更容易被熟人声线和紧急措辞带偏。','涉钱、涉验证码、涉下载软件、涉屏幕共享的要求，都必须转入二次验证流程。']},
]
const signals=[
 {title:'画面线索',items:['嘴型闭合与爆破音不同步，尤其是需要明显闭嘴的发音。','耳朵、发际线、眼镜边缘、首饰、下巴轮廓在转头时出现抖动、模糊或穿帮。','肤色、阴影、反光方向不一致，脸部亮度与环境光源关系异常。','表情和头部动作偏僵，微表情少，眨眼节奏不自然。']},
 {title:'音频线索',items:['语气过于平直或突然切换，停顿像被拼接，气口和呼吸感不足。','背景噪音与场景不匹配，例如说在户外却没有环境声变化。','长句子能量分布过于均匀，缺少真人自然的重音和情绪波动。','对方刻意避免自由对话，常把你引向转账、验证码或下载操作。']},
 {title:'行为线索',items:['对方要求立刻转账、保密、不要挂断、不要联系本人或不要走正常流程。','让你切到陌生平台、加入临时群、下载远程控制或屏幕共享软件。','信息请求超出关系边界，例如熟人突然要身份证、银行卡、验证码、录屏。','越是真实关系，越要反向确认，因为骗子正是利用你不好意思怀疑的心理。']},
]
const steps=[['暂停','先把节奏抢回来','一旦对方开始催钱、催码、催安装，第一动作不是配合，而是主动中断当前通话或聊天窗口。'],['复核','换一个渠道联系真人','使用你自己保存过的电话号码、企业通讯录、线下联系人或面对面复核，不要回拨对方刚发来的号码。'],['追问','问只有真人才知道的问题','不要问可被公开资料猜到的信息，优先问共同经历、内部流程、线下细节、约定暗号。'],['留痕','保留链接、账号、录音和截图','如果已经涉及诈骗诱导，及时保留证据并向平台、学校、单位或警方求助。']]
const resources=[
 ['Toolify: AI deepfake 完全指南：定义、技术风险及防范措施','中文综述，覆盖 deepfake 定义、实现方式、风险与防范措施','resource-cover-toolify-deepfake.jpg','https://www.toolify.ai/zh/ai-news-cn/ai-deepfake%E5%AE%8C%E5%85%A8%E6%8C%87%E5%8D%97%E5%AE%9A%E4%B9%89%E6%8A%80%E6%9C%AF%E9%A3%8E%E9%99%A9%E5%8F%8A%E9%98%B2%E8%8C%83%E6%8E%AA%E6%96%BD-3579569'],
 ['InfoQ: Deepfake 2020 发展报告','从技术与滥用现状切入，补充中文案例和风险背景','resource-cover-infoq-deepfake-2020.jpg','https://www.infoq.cn/article/U7jtW13wAskcH2Mpl918'],
 ['Kaspersky: 保护自己免受 Deepfake 侵害','聚焦 deepfake 识别与公众自我保护','resource-cover-kaspersky-deepfake.jpg','https://www.kaspersky.com.cn/resource-center/threats/protect-yourself-from-deep-fake'],
 ['网易: 黑科技 DeepFake 究竟有多危险？','补充 deepfake 滥用风险和社会影响背景','resource-cover-163-deepfake.jpg','https://www.163.com/dy/article/I1I7M8DP0537SZVN.html'],
 ['网易: 深度伪造原理分析及实战','补充 deepfake 生成流程与算法背景','resource-cover-163-deepfake-principle.png','https://www.163.com/dy/article/GH47R1DH0511FSTO.html'],
 ['CSDN: deepface 框架讲解','人脸识别与属性分析技术背景','resource-cover-csdn-deepface.png','https://blog.csdn.net/weixin_46211269/article/details/124095978'],
 ['World Economic Forum: How to spot deepfakes','公众视角的 deepfake 识别要点','resource-cover-wef-deepfake.jpg','https://www.weforum.org/stories/2020/01/how-to-spot-a-deepfake/'],
 ['MIT Sloan: Deepfakes, explained','从技术和商业风险角度解释 deepfake 机制','resource-cover-mit-sloan-deepfake.webp','https://mitsloan.mit.edu/ideas-made-to-matter/deepfakes-explained'],
 ['MIT Media Lab: Detect DeepFakes','深伪检测研究项目与方法概览','resource-cover-mit-media-detect-deepfakes.png','https://www.media.mit.edu/projects/detect-fakes/overview/'],
]
</script>
<template><section class="edu-hero"><div class="edu-hero__copy"><p class="eyebrow">Education Channel</p><h1>识别 deepfake、AI 换脸、AI 换音，<br/>不只靠“看起来像不像”。</h1><p class="edu-hero__lede">从概念解析、典型案例到识别方法，带你快速了解深度伪造的风险与防范。</p><div class="hero__actions"><RouterLink class="button button--primary" to="/quiz">开始反诈闯关</RouterLink><RouterLink class="button button--secondary" to="/detect/video">体验视频检测</RouterLink></div><div class="edu-hero__metrics"><div><span>03</span><strong>核心主题</strong><small>deepfake / 换脸 / 换音</small></div><div><span>04</span><strong>验证动作</strong><small>暂停、复核、追问、留痕</small></div><div><span>12</span><strong>答题题库</strong><small>覆盖熟人诈骗、平台信息与版权意识</small></div></div></div><div class="edu-hero__visual"><div class="edu-orbit edu-orbit--one"/><div class="edu-orbit edu-orbit--two"/><div class="edu-monitor"><div class="edu-monitor__line"><span>REALITY CHECK</span><strong>身份核验优先于画面直觉</strong></div><div class="edu-monitor__grid"><div><small>Face</small><p>边缘、口型、反光、转头</p></div><div><small>Voice</small><p>气口、停顿、情绪、背景声</p></div><div><small>Context</small><p>账号、链接、域名、流程</p></div><div><small>Action</small><p>停下、回拨、复核、留痕</p></div></div></div></div></section>
<section class="section-block final-cta"><div><p class="eyebrow">Already Familiar?</p><h2>如果这些概念你已经掌握，可以直接进入闯关答题。</h2></div><div class="hero__actions"><RouterLink class="button button--primary" to="/quiz">直接进入闯关答题</RouterLink><RouterLink class="button button--ghost" to="/detect/video">返回业务页面</RouterLink></div></section>
<section class="section-block"><div class="section-heading"><p class="eyebrow">Core Topics</p><h2>先讲清概念边界，再谈怎么防</h2><p>真正的风险判断需要拆开看：它替换了什么、冒充了谁、想推动你做什么。</p></div><div class="edu-topic-grid"><article v-for="track in tracks" :key="track.label" class="edu-topic"><span class="edu-topic__label">{{ track.label }}</span><h3>{{ track.title }}</h3><p>{{ track.summary }}</p><ul class="edu-list"><li v-for="point in track.points" :key="point">{{ point }}</li></ul></article></div></section>
<section class="section-block"><div class="section-heading"><p class="eyebrow">How To Spot</p><h2>别把注意力全放在“真假脸”，行为和来源同样重要</h2><p>更稳定的危险信号包括催转账、要验证码、阻止回拨和阻止第三方确认。</p></div><div class="edu-signal-grid"><article v-for="group in signals" :key="group.title" class="edu-signal"><h3>{{ group.title }}</h3><ul class="edu-list"><li v-for="entry in group.items" :key="entry">{{ entry }}</li></ul></article></div></section>
<section class="section-block"><div class="section-heading"><p class="eyebrow">Verification Loop</p><h2>真正管用的是四步验证法</h2><p>它能在你慌张、被催促、信息不完整的时候继续工作。</p></div><div class="edu-steps"><article v-for="step in steps" :key="step[0]" class="edu-step"><span class="edu-step__tag">{{ step[0] }}</span><h3>{{ step[1] }}</h3><p>{{ step[2] }}</p></article></div></section>
<section class="section-block"><div class="section-heading"><p class="eyebrow">Source Library</p><h2>深伪案例与防范指南</h2><p>精选深度伪造相关案例和实用知识，让你更直观地了解它、识别它、远离它。</p></div><div class="edu-resource-groups"><section class="edu-resource-group edu-resource-group--compact"><div class="edu-resource-list"><a v-for="resource in resources" :key="resource[0]" class="edu-resource" :href="resource[3]" target="_blank" rel="noreferrer"><div class="edu-resource__cover"><img :src="`/static/images/${resource[2]}`" :alt="resource[0]" loading="lazy"/></div><strong>{{ resource[0] }}</strong><span>{{ resource[1] }}</span></a></div></section></div></section></template>
